### ISSUE TITLE
php: symbol lookup error: /usr/lib/php/20210902/gearman.so: undefined symbol: ZVAL_NEW_ARR

### ISSUE THREAD

**Issue by tsiura** [php/pecl-networking-gearman#11]
Got an error 
`php: symbol lookup error: /usr/lib/php/20210902/gearman.so: undefined symbol: ZVAL_NEW_ARR`
while trying to run reverse_worker.php

libgearman8:amd64                     1.1.18+ds-3.1ubuntu1

pecl extension: gearman 2.1.0 (stable)

Linux 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.1.0 (cli) (built: Nov 25 2021 20:22:03) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.0, Copyright (c), by Zend Technologies

**Comment by oleg-st** [comment]
I think it fixed by @remicollet in master (https://github.com/php/pecl-networking-gearman/commit/7da13e4babc17067b2b45d6b37041c3c8ed91637)

**Comment by tsiura** [comment]
Yes it is, thanks ) New tag needed)
