### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by Visualq** [php/pecl-networking-gearman#20]
In a few days PHP 8.2 will be released, is it possible to get the extension to support PHP 8.2?

**Comment by Visualq** [comment]
It does indeed. I got the message that the extension was not able to build on anything less than PHP 8.1.99. But this is no longer the case.

**Comment by ryandesign** [comment]
The latest released version of pecl-networking-gearman, 2.1.0, is not compatible with php 8.1 or later as described in #16. A new stable version should be released.

**Comment by igordeveloper** [comment]
Is there a deadline for a release with php 8.2 support?

**Comment by esabol** [comment]
Ping @rlerdorf . Could you release a new version for PHP 8.2 please?

**Comment by igordeveloper** [comment]
> Ping @rlerdorf . Could you release a new version for PHP 8.2 please?

Any news? tks
