### ISSUE TITLE
Gearman client add server errors

### ISSUE THREAD

**Issue by tree28** [php/pecl-networking-gearman#28]
Hello,

Some background, the error, and the client code used (ie. modification to add remote client).

Background:
I am a new Gearman user. I have a fresh machine running Ubuntu 24.04 on AWS with Gearman installed successfully as per the version test given [here](https://gearman.org/getting-started/). I am running PHP 8.3. 

I can run all the provided Gearman php demos on the server (note a recent issue logged about "do" as opposed to "doNormal"). I am now trying to send a Gearman job (the reverse hello world string demo) to a second server for processing. The servers are on the same subnet and can ping each other, there are no firewalls blocking traffic.

When sending the job I receive the following error:

Error:
_**PHP Fatal error:  Uncaught GearmanException: Failed to set exception option in /var/www/client.php:7
Stack trace:
#0 /var/www/client.php(7): GearmanClient->addServer()
#1 {main}**_

Client code used (note modification to add remove client via addServer):
`<?php

// Create our client object
$client = new GearmanClient();

// Add a server (modified where X.X.X.X is the actual IP address of given machine)

$client->addServer('X.X.X.X','4730'); // by default host/port will be "localhost" & 4730

echo "Sending job\n";

// Send reverse job
$result = $client->doNormal("reverse", "Hello!");
if ($result) {
  echo "Success: $result\n";
}
?>`

Observation:
Help is greatly appreciated. I do not know if this is an error from my end or a possible bug.

**Comment by esabol** [comment]
@tree28: Can you clarify the exact version number of the Gearman PHP extension you have installed?

**Comment by tree28** [comment]
Gearman version: 1.1.20+ds
PHP version: 8.3.6 (cli) (built: Apr 15 2024 19:21:47) (NTS)

**Comment by esabol** [comment]
@tree28: Wrong version number. That's either your libgearman.so version number or your gearmand version. Either way, that's not what I asked for, which was the version of the Gearman PHP extension. Refer to https://github.com/php/pecl-networking-gearman/releases for the PHP extension release numbers. Basically, if you're not using the latest version, then you need to upgrade.

**Comment by tree28** [comment]
To confirm:

The following work:
$worker->addServer();
$worker->addServer('localhost',4730);

The following does not work (where X.X.X.X is a reachable ip)
$worker->addServer('X.X.X.X',4730);

**Comment by esabol** [comment]
@tree28 wrote:
> Understood but unfortunately that's the number that comes up from using your method as well as using the command: `gearadmin --server-version`

OK, try this:
```php
<?php
print phpversion("gearman") . "\n";
?>
```

**Comment by tree28** [comment]
@esabol 
done - the result is: 2.1.2

**Comment by esabol** [comment]
OK, good. That is the latest version of the Gearman PHP extension.

> $client->addServer('10.0.1.140','4730'); // fatal error

What does `gearadmin -h 10.0.1.140 -p 4730 --status` report from the host that you are running PHP on?

**Comment by tree28** [comment]
@esabol
`Error: Error connecting to 10.0.1.140`

**Comment by esabol** [comment]
Well, then the problem isn't with the Gearman PHP extension. You have a networking problem. If you can't connect to 10.0.1.140 from the command line, there should be no expectation that it should work from inside PHP.
