### ISSUE TITLE
How to start a worker on reboot

### ISSUE THREAD

**Issue by tree28** [php/pecl-networking-gearman#29]
Hello,
I'm new to Gearman. I've been able to write worker and client PhP scripts that successfully execute tasks. 

**Background:**
I have also been trying to implement crontab on my gearman server so that the worker php scripts are loaded automatically on restarting the machine.

ie.
`crontab -e`
`@reboot php /var/www/scripts_gearman/worker_one.php`
`@reboot php /var/www/scripts_gearman/worker_two.php`

**Observation (Using crontab)**
While the scripts do load via crontab (see initial status) they are not stable. For example after running the client (ie. client_one) for worker_one the worker produces _**no result**_ and upon reviewing its status (see reviewed status) no available workers are report.

Reboot
(crontab initializes gearman workers)

Initial status (on reboot):
`gearadmin -h 127.0.0.1 -p 4730 --status`
`one	0	0	1`
`two	0	0	1`

client one now called (triggering a worker one process)

Reviewed status (after client one called):
`gearadmin -h 127.0.0.1 -p 4730 --status`
`one	0	0	0`
`two	0	0	1`

**Observation (using tutorial example)**
The getting started tutorial [here](https://gearman.org/getting-started/) shows the php cli method for running a worker. This method is stable. For example after running the same client (ie. client_one) for worker_one the worker successfully produces _**a result**_ and upon reviewing its status the worker continues to be available.

Initialize worker one
`php /var/www/scripts_gearman/worker_one.php &`

Initial status (after initializing worker one):
`gearadmin -h 127.0.0.1 -p 4730 --status`
`one	0	0	1`
`two	0	0	1`

client one now called (triggering a worker one process)

Reviewed status (after client one called):
`gearadmin -h 127.0.0.1 -p 4730 --status`
`one	0	0	1`
`two	0	0	1`

**Question:**
Is the crontab behavior expected? How can gearman workers be run correctly from crontab? What is the best way to initialize a worker on restarting a machine? _Note the machine is a fresh ubuntu 24.04 server._

**Comment by ngmlabs** [comment]
Hello,

Running your workers in supervisord or as systemd unit files would be more appropriate than running them as cron jobs.

**Comment by tree28** [comment]
@ngmlabs 
Sincerely appreciate the tip – are there any simple examples for Gearman that you can point me toward?

**Comment by tree28** [comment]
@ngmlabs,

Thanks for the reference. The instructions well successful! For anyone looking for a recipe here is the code I decided to use:

```
[Unit]
Description=MyGearmanWorker
Requires=memcached.service mysql.service
After=network.target
[Service]
User=www-data
Type=simple
ExecStart=/usr/bin/php /var/www/MyGearmanWorker.php
Restart=always
[Install]
WantedBy=default.target
```
